export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const PRODUCTS_DOWNLOADING_START = 'PRODUCTS_DOWNLOADING_START';
export const PRODUCTS_DOWNLOADING_SUCCESS = 'PRODUCTS_DOWNLOADING_SUCCESS';
export const PRODUCTS_DOWNLOADING_ERROR = 'PRODUCTS_DOWNLOADING_ERROR';
